### ISSUE TITLE
Recreate the Ninja for TTT2

### ISSUE THREAD

**Issue by Alf21** [iViscosity/More-TTT-Roles#1]
I just wanna ask whether you would recreate the ninja for TTT2? (https://github.com/Alf21/TTT2)

**Comment by Alf21** [comment]
It‘s a completely rewritten version of TTT2 with an improvement of nearly every system to better support the dynamical addition of roles and be as fast as the normal TTT. There are already different bugfree roles that are added through external add-ons like the survivalist. E.g. the Networking system is faster than in TTT. It knows, which player is aware of another player to save and lower network usage. In addition to that, it‘s possible to easily hack the roles for a specific player on the server, to modify the role display and syncing. There are different other features like the weaponshop (build your own shops ingame), TTT2 ULX (save ConVars permanently), RoleVote (vote the roles that could be selected) or other things ^^
Would be nice if you could use it, because I think you know how to program in Lua and to improve compatibility :D

**Comment by iViscosity** [comment]
> It‘s a completely rewritten version of TTT with an improvement of nearly every system to better support the dynamical addition of roles and be as fast as the normal TTT. There are already different bugfree roles that are added through external add-ons like the survivalist. E.g. the Networking system is faster than in TTT. It knows, which player is aware of another player to save and lower network usage. In addition to that, it‘s possible to easily hack the roles for a specific player on the server, to modify the role display and syncing. There are different other features like the weaponshop (build your own shops ingame), TTT2 ULX (save ConVars permanently), RoleVote (vote the roles that could be selected) or other things ^^
> Would be nice if you could use it, because I think you know how to program in Lua and to improve compatibility :D

I will definitely look into it.

**Comment by iViscosity** [comment]
Just going to leave [this here](https://github.com/iViscosity/TTT2)
